---
name: Net-Pcap
version: 0.19
author:
  - 'Sébastien Aperghis-Tramoni <sebastien@aperghis.net>'
abstract: Interface to pcap(3) LBL packet capture library
license: perl
build_requires:
  Test::More: 0.45
installdirs:  site
distribution_type: module
